import type { ImportJob, Transaction } from "@expenses/shared";

const now = "2026-04-01T08:00:00.000Z";

export const mockTransactions: Transaction[] = [
  {
    id: "txn-101",
    externalId: "upi-101",
    date: "2026-04-01T07:35:00.000Z",
    amount: 265,
    currency: "INR",
    direction: "debit",
    status: "completed",
    merchant: "Swiggy",
    merchantNormalized: "swiggy",
    description: "Breakfast order paid with UPI",
    paymentMethod: "UPI",
    source: "sms",
    sourceRef: "sms:1",
    upiHandle: "munna@oksbi",
    category: "Food",
    categoryConfidence: 0.97,
    isAutoCategorized: true,
    tags: ["meal", "quick-order"],
    rawMessage: "Paid Rs 265 to Swiggy via UPI",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "txn-102",
    externalId: "card-102",
    date: "2026-03-31T13:15:00.000Z",
    amount: 1499,
    currency: "INR",
    direction: "debit",
    status: "completed",
    merchant: "Amazon",
    merchantNormalized: "amazon",
    description: "Card payment for home office accessories",
    paymentMethod: "Card",
    source: "email",
    sourceRef: "mail:9",
    accountLast4: "4242",
    cardNetwork: "Visa",
    category: "Shopping",
    categoryConfidence: 0.91,
    isAutoCategorized: true,
    tags: ["office"],
    rawMessage: "Your card ending 4242 was charged INR 1499.",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "txn-103",
    externalId: "upi-103",
    date: "2026-03-30T16:45:00.000Z",
    amount: 620,
    currency: "INR",
    direction: "debit",
    status: "completed",
    merchant: "BigBasket",
    merchantNormalized: "bigbasket",
    description: "Weekly groceries",
    paymentMethod: "UPI",
    source: "sms",
    sourceRef: "sms:2",
    upiHandle: "munna@ybl",
    category: "Groceries",
    categoryConfidence: 0.96,
    isAutoCategorized: true,
    tags: ["home"],
    rawMessage: "Paid Rs 620 to BigBasket",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "txn-104",
    date: "2026-03-29T11:05:00.000Z",
    amount: 240,
    currency: "INR",
    direction: "debit",
    status: "completed",
    merchant: "Uber",
    merchantNormalized: "uber",
    description: "Airport ride",
    paymentMethod: "Card",
    source: "email",
    accountLast4: "4242",
    cardNetwork: "Visa",
    category: "Transport",
    categoryConfidence: 0.94,
    isAutoCategorized: true,
    rawMessage: "Uber trip charged to your card",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "txn-105",
    date: "2026-03-28T09:00:00.000Z",
    amount: 799,
    currency: "INR",
    direction: "debit",
    status: "completed",
    merchant: "Airtel",
    merchantNormalized: "airtel",
    description: "Monthly mobile recharge",
    paymentMethod: "UPI",
    source: "statement_upload",
    category: "Recharge",
    categoryConfidence: 0.89,
    isAutoCategorized: true,
    createdAt: now,
    updatedAt: now
  },
  {
    id: "txn-106",
    date: "2026-03-26T17:10:00.000Z",
    amount: 4250,
    currency: "INR",
    direction: "debit",
    status: "completed",
    merchant: "Landlord",
    merchantNormalized: "landlord",
    description: "Rent transfer",
    paymentMethod: "NetBanking",
    source: "manual",
    category: "Rent",
    categoryConfidence: 1,
    isAutoCategorized: false,
    note: "April partial rent",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "txn-107",
    date: "2026-03-24T08:20:00.000Z",
    amount: 380,
    currency: "INR",
    direction: "debit",
    status: "completed",
    merchant: "Apollo Pharmacy",
    merchantNormalized: "apollo pharmacy",
    description: "Medicines",
    paymentMethod: "UPI",
    source: "sms",
    category: "Health",
    categoryConfidence: 0.93,
    isAutoCategorized: true,
    createdAt: now,
    updatedAt: now
  },
  {
    id: "txn-108",
    date: "2026-03-21T19:20:00.000Z",
    amount: 540,
    currency: "INR",
    direction: "debit",
    status: "completed",
    merchant: "PVR Cinemas",
    merchantNormalized: "pvr cinemas",
    description: "Movie night",
    paymentMethod: "Card",
    source: "email",
    accountLast4: "4242",
    cardNetwork: "Visa",
    category: "Entertainment",
    categoryConfidence: 0.92,
    isAutoCategorized: true,
    createdAt: now,
    updatedAt: now
  },
  {
    id: "txn-109",
    date: "2026-03-18T06:30:00.000Z",
    amount: 95,
    currency: "INR",
    direction: "debit",
    status: "completed",
    merchant: "Metro",
    merchantNormalized: "metro",
    description: "Metro recharge",
    paymentMethod: "Wallet",
    source: "statement_upload",
    category: "Transport",
    categoryConfidence: 0.88,
    isAutoCategorized: true,
    createdAt: now,
    updatedAt: now
  },
  {
    id: "txn-110",
    date: "2026-03-14T15:45:00.000Z",
    amount: 1750,
    currency: "INR",
    direction: "debit",
    status: "completed",
    merchant: "Makemytrip",
    merchantNormalized: "makemytrip",
    description: "Bus booking",
    paymentMethod: "UPI",
    source: "email",
    category: "Travel",
    categoryConfidence: 0.86,
    isAutoCategorized: true,
    createdAt: now,
    updatedAt: now
  }
];

export const mockImportJobs: ImportJob[] = [
  {
    id: "job-1",
    source: "statement_upload",
    status: "completed",
    totalRecords: 46,
    importedRecords: 44,
    duplicateRecords: 2,
    startedAt: "2026-03-31T06:10:00.000Z",
    finishedAt: "2026-03-31T06:11:20.000Z"
  },
  {
    id: "job-2",
    source: "sms",
    status: "running",
    totalRecords: 12,
    importedRecords: 9,
    duplicateRecords: 0,
    startedAt: "2026-04-01T05:40:00.000Z"
  }
];
